name: DevSecOps Vulnerable Lab Pipeline

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch: # Manuel tetiklemek için

jobs:
  deploy-lab:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-on-version: '20' # Juice Shop için stabil bir sürüm

      - name: Install and Start Juice Shop (Docker ile)
        run: |
          echo "Juice Shop Docker container'ı başlatılıyor..."
          docker run -d -p 3000:3000 --name bami-juice-shop baimaj/juice-shop
          
      - name: Check Application Status
        run: |
          sleep 10
          curl -I http://localhost:3000
